### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SebastianOpiyo** [CsqLang/Csq#162]
Hi @AniketKumar2500, 

I have been looking around for any sort of documentation on what the code does so far, amongst other code implementation details to start with. Do we have any?
I wish to be a contributor. 

Thanks.

**Comment by AniketKumar2500** [comment]
We are having a documentation how to write in Csq but there is no documentation for the backend code but we hope we will have one.

**Comment by AniketKumar2500** [comment]
For now you could visit readme.md in Runtime directory to see the working of the memory in Csq.

**Comment by usmanmusa1920** [comment]
Implementing backend documentation would really sickk, currently I am not well satisfy (understanding) on what is going on with most of the backend

**Comment by AniketKumar2500** [comment]
Are you not getting how backend's code compiling logic works or not getting how it's code works?

**Comment by usmanmusa1920** [comment]
Surely I am, but the backend documentation make it ease!

**Comment by AniketKumar2500** [comment]
Ok so currently we are making the code more easy by using python and we are working to make the documentation.

**Comment by usmanmusa1920** [comment]
That is a very good idea!
