### ISSUE TITLE
Proposal for using Python 3 in CSQ4

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq#164]
I think we can use Python in the development of Csq4, but not completely. We can use it only for the task of reading .csq files and generating .cpp files.

In the Csq4 project, there are the following files: [AST, Builtin, Grammar, Parser, Runtime, Tokenizer]. The Builtin and Runtime files are used after generating the .cpp file. We can develop these files in C++ language.

The remaining files, Tokenizer, Grammar, Parser, and Ast, are used to generate the .cpp code. For this, we can use Python. Python is easy, so we can do this work in Python. The core of Csq is in C++, so the performance of the Csq language will remain fast after compilation.

Here is a more detailed explanation of the proposal:

1. The Builtin and Runtime files are used to provide the core functionality of the Csq language. These files are written in C++, so they will be compiled into native machine code. This will ensure that the Csq language performs well.
2. The Tokenizer, Grammar, Parser, and Ast files are used to parse Csq code and generate .cpp code. These files can be written in Python. Python is a scripting language, so it is easy to use and maintain.
3.  By using Python for the parsing and code generation tasks, we can make the development of Csq4 easier and more efficient.

I think this proposal is a good idea. It would make it easier to develop Csq4 and would improve the performance of the language.

**Comment by AniketKumar2500** [comment]
Indeed a good idea.
 But i would rather say have both C/C++ and Python implementations because 
in case of small source code we can easily use Python it will be fast.
in case of big code it will require more processing power and we want minimum memory usage so C/C++ will be good there.
And one more stuff.

I once proposed an idea of a new keyword cimport to import existing C/C++ code so what i thought was that during runtime itself user can import AST, Parser and Tokenizer headerfiles and change them according to their need which will make Csq4 extensible like Lisp, Nim etc improving productivity and metaprogramming so what i would suggest that we should have both.

**Comment by WithSJ** [comment]
No, CSQ code can be converted to CPP code using Python. The logic and core of the CSQ code will remain the same in CPP. The compile time may increase due to Python, but development will be much faster.

**Comment by AniketKumar2500** [comment]
I liked the proposal hope it will be helpfull but the we have to remake the parser, AST and tokenizer. until its done we shall let Cpp code exist.

**Comment by WithSJ** [comment]
it good to have both cpp and python code both.

**Comment by AniketKumar2500** [comment]
But it's not gonna be easy to create parser again.

**Comment by AniketKumar2500** [comment]
I hope this proposal found an end since all the features are implemented in Python which were there in C/C++.

**Comment by WithSJ** [comment]
Right. i think we can remove cpp code of Csq Compiler

**Comment by WithSJ** [comment]
Have another suggestion regarding the repository name. I propose renaming it from 'CSQ4' to simply 'Csq.' This change reflects the fact that all previous versions were developed entirely in C++, and now, with the introduction of the Csq Language, we are embarking on a new journey

**Comment by AniketKumar2500** [comment]
Good thought.

**Comment by AniketKumar2500** [comment]
May i change the name of repo to Csq

**Comment by WithSJ** [comment]
yes. and than we start using Semantic Versioning (check  #200)

**Comment by AniketKumar2500** [comment]
Now if we are adding any new feature we should use github releases shouldn't we?

**Comment by WithSJ** [comment]
Nha,,,, i don't think right now Csq need github release.  

now i am close this issue
