### ISSUE TITLE
Write a roadmap of the project

### ISSUE THREAD

**Issue by gekkowrld** [CsqLang/Csq#197]
[Suggestion]
This is not really to write a full blown roadmap.
I want some order in the development, what features should be implemented and their priority.
Let's say we want to implement following data types: int, float, char.
We can then say this is the order of importance:
- char
- int
- float

With something like this model, if a feature is to be implemented, we can be all aware of what to do.
This is a contrast of what we are doing now.

All the opinions are welcome

**Comment by AniketKumar2500** [comment]
I Suggest we should move forth to development of classes.
