### ISSUE TITLE
(Proposal) Use union for cell value

### ISSUE THREAD

**Issue by Krobix** [CsqLang/Csq#203]
Hi,

Let me know if I should move this to the other "clean-up" issue, but I thought that since it also could help performance and is a pretty big change, I should put it here.

In memory.h, you have the Cell struct, which as of now, includes the following properties:

```
int ival;
    double fval;
    string sval;
    vector<Cell> array;
```
    
The way that this is done could cause problems, i.e if you change the type that a cell contains, then you might end up forgetting to erase the old value, and you have to remember and manage that manually. Additionally, I think it's a little unorganized.

To make the code more organized and improve memory usage, you could use a union for this, this is an example:

```
union CellValue {
    int ival;
    double fval;
   string sval;
   vector<Cell> array;
}
```

And then in the `Cell` struct, you could simply use one property, i.e. `CellValue value`, and then use `value.ival` to access the int value.

**Comment by AniketKumar2500** [comment]
Well your idea is correct it would be memory efficient, but a problem with C++ is there, that a union couldn't hold a non trivial constructor of a class which is in this case std::string due to which it will not compile.
