### ISSUE TITLE
[Suggestion]: Use `/opt/` directory and then create a soft link to `/usr/local/bin/csq`

### ISSUE THREAD

**Issue by gekkowrld** [CsqLang/Csq#247]
As the project grows and factoring in people's different configurations it is better that all the project files be stored in a statistically common place.
The /opt/ directory as explained here <https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html>, <https://www.baeldung.com/linux/opt-directory>, <https://www.pathname.com/fhs/2.2/fhs-3.12.html> and <https://stackoverflow.com/questions/12649355/what-does-opt-mean-as-in-the-opt-directory-is-it-an-abbreviation> is a good place to place the project files.

Of course as all things Linux (*that's so Linux) not all distros follow this convention or have them `/usr/local/` is another popular place. This however isn't a big problem to fix just checking for directory existence.

I'll restructure the files to conform to the standard for easier installation.

**Comment by WithSJ** [comment]
Your suggestion is good, but we will address it after resolving issue #245.
